node_js:
- "4"
- "6"
- "7"
language: node_js
install:
- npm install
- npm install -g codecov istanbul
script:
- npm run $TARGET
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- --timeout 5s -R spec $TESTS
- codecov
